### ISSUE TITLE
开发工具不能解析 &

### ISSUE THREAD

**Issue by mgpeng** [Tencent/weui-wxss#100]
下载，然后在开发工具里运行，报错：
```
Error:
    in File: ./example/index.wxss
unexpected "&" at pos 146
   &:before, &:after {.....}
   
    &_show{ .....
```

**Comment by mgpeng** [comment]
后 npm install, 许多警告，再 npm run start, 又出错：
```
Mac:src apple$ npm run start

> weui-wxss@1.1.1 start /Users/apple/Documents/xixijiu_ng-md/weui-wxss-master/src
> gulp

assert.js:42
  throw new errors.AssertionError({
  ^

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (/Users/apple/Documents/xixijiu_ng-md/weui-wxss-master/src/node_modules/undertaker/lib/set-task.js:10:3)
    at Gulp.task (/Users/apple/Documents/xixijiu_ng-md/weui-wxss-master/src/node_modules/undertaker/lib/task.js:13:8)
    at Object.<anonymous> (/Users/apple/Documents/xixijiu_ng-md/weui-wxss-master/src/gulpfile.js:56:6)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! weui-wxss@1.1.1 start: `gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the weui-wxss@1.1.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/apple/.npm/_logs/2018-12-27T15_09_06_407Z-debug.log
```

**Comment by chunge66** [comment]
[Try this](https://github.com/Tencent/weui-wxss/issues/78#issuecomment-417003181)

**Comment by BearJ** [comment]
@mgpeng 请引用dist目录下的文件，不要直接引用src里的哈

**Comment by mgpeng** [comment]
非常感谢！
